/**
 * SEO keyword corpus for Crabbe Crabbe & Co.
 * Ghana-based firm with international practice reach.
 */

const FIRM_NAMES = [
  "Crabbe Crabbe & Co",
  "Crabbe Crabbe and Co",
  "Crabbe Crabbe & Co law firm",
  "Crabbe Crabbe & Co lawyers",
  "Crabbe Crabbe & Co attorneys",
  "Crabbe Crabbe & Co legal services",
  "Crabbe Crabbe & Co Ghana",
  "Crabbe Crabbe & Co Accra",
];

const LOCATIONS = [
  "Ghana",
  "Accra",
  "Greater Accra",
  "Tse Addo",
  "Weija",
  "East La",
  "Trade Fair Accra",
  "West Africa",
  "Africa",
  "international",
  "global",
  "cross-border",
];

const FIRM_TYPES = [
  "law firm",
  "lawyers",
  "attorneys",
  "solicitors",
  "barristers",
  "legal counsel",
  "legal advisors",
  "legal consultants",
  "chambers",
  "advocates",
  "legal practice",
  "legal team",
  "law office",
  "legal firm",
];

const PRACTICE_AREAS = [
  "corporate law",
  "commercial law",
  "banking law",
  "finance law",
  "banking and finance",
  "litigation",
  "dispute resolution",
  "arbitration",
  "mediation",
  "land law",
  "real estate law",
  "property law",
  "conveyancing",
  "labour law",
  "employment law",
  "immigration law",
  "tax law",
  "tax advisory",
  "intellectual property",
  "energy law",
  "oil and gas law",
  "mining law",
  "natural resources",
  "debt recovery",
  "debt enforcement",
  "insolvency",
  "restructuring",
  "regulatory compliance",
  "corporate governance",
  "AML compliance",
  "CFT compliance",
  "anti-money laundering",
  "data protection",
  "family law",
  "matrimonial law",
  "criminal law",
  "criminal defence",
  "regulatory defence",
  "contract law",
  "mergers and acquisitions",
  "M&A",
  "joint ventures",
  "shareholder agreements",
  "company formation",
  "due diligence",
  "project finance",
  "securities law",
  "capital markets",
  "trade law",
  "international trade",
  "maritime law",
  "aviation law",
  "competition law",
  "antitrust",
  "public law",
  "administrative law",
  "constitutional law",
  "human rights law",
  "environmental law",
  "ESG compliance",
  "fiduciary duties",
  "trust law",
  "estate planning",
  "wills and probate",
  "notary public",
  "legal drafting",
  "legal opinions",
  "legal representation",
  "court representation",
  "Supreme Court Ghana",
  "High Court Ghana",
  "Commercial Court",
];

const CLIENT_TYPES = [
  "financial institutions",
  "banks",
  "corporations",
  "businesses",
  "SMEs",
  "startups",
  "public sector",
  "government entities",
  "NGOs",
  "individuals",
  "high net worth clients",
  "multinationals",
  "foreign investors",
  "diaspora clients",
  "international clients",
];

const INTENT = [
  "best law firm",
  "top lawyers",
  "trusted legal counsel",
  "experienced attorneys",
  "affordable lawyers",
  "boutique law firm",
  "full service law firm",
  "business lawyers",
  "corporate lawyers Ghana",
  "litigation lawyers Ghana",
  "banking lawyers Ghana",
  "property lawyers Accra",
  "legal consultation",
  "legal advice",
  "book appointment lawyer",
  "law firm near me",
  "lawyer consultation Accra",
  "Ghana legal services",
  "international law firm Ghana",
  "Ghana law firm international clients",
];

const GOVERNANCE = [
  "governance consultant",
  "compliance consultant",
  "risk management",
  "operational risk",
  "board advisory",
  "board secretary services",
  "institutional governance",
  "banking regulation",
  "fraud prevention",
  "negotiable instruments",
  "legal profession rules Ghana",
  "General Legal Council",
  "Ghana Bar Association",
  "enrolled solicitor Ghana",
  "barrister Ghana",
];

const EXTRA = [
  "legal services Ghana",
  "law firm Accra Ghana",
  "law firm Tse Addo",
  "law firm Weija office",
  "Ghana corporate lawyers",
  "Ghana commercial litigation",
  "Ghana banking legal advice",
  "Ghana debt recovery lawyers",
  "Ghana land dispute lawyers",
  "Ghana employment dispute lawyers",
  "Ghana tax lawyers",
  "Ghana regulatory lawyers",
  "Ghana international arbitration",
  "Africa law firm",
  "West Africa legal services",
  "foreign law firm Ghana",
  "Ghana cross-border transactions",
  "Ghana foreign investment law",
  "Ghana company registration lawyers",
  "Ghana contract lawyers",
  "Ghana lease lawyers",
  "Ghana mortgage lawyers",
  "Ghana labour tribunal",
  "Ghana court lawyers",
  "Ghana appellate lawyers",
  "Ghana legal representation",
  "Ghana solicitor services",
  "Ghana barrister services",
  "professional legal ethics Ghana",
  "confidential legal advisory",
  "strategic legal solutions",
  "practical legal advice",
  "commercially focused lawyers",
  "solution-driven law firm",
  "client-focused law firm",
  "integrity law firm Ghana",
  "innovation legal practice",
  "excellence legal services",
  "trusted advocacy Ghana",
  "legal excellence Ghana",
  "law firm East La",
  "law firm behind Trade Fair",
  "Winneba legal services",
  "Accra law chambers",
  "Ghana managing partner law firm",
  "senior partner law firm Ghana",
  "qualified lawyers Ghana",
  "experienced legal team Ghana",
  "paralegal support law firm",
  "legal operations Ghana",
  "institutional legal support",
  "financial sector lawyers Ghana",
  "corporate transactions Ghana",
  "security perfection Ghana",
  "lending transactions Ghana",
  "borrower counsel Ghana",
  "lender counsel Ghana",
  "investor counsel Ghana",
  "share purchase agreement Ghana",
  "asset purchase Ghana",
  "commercial lease Ghana",
  "development agreement Ghana",
  "title due diligence Ghana",
  "land acquisition Ghana",
  "property dispute Ghana",
  "redundancy advice Ghana",
  "disciplinary proceedings Ghana",
  "workplace policies Ghana",
  "visa advice Ghana",
  "work permit Ghana",
  "residence permit Ghana",
  "GRA tax dispute Ghana",
  "Ghana Revenue Authority lawyer",
  "oil and gas advisory Ghana",
  "mining advisory Ghana",
  "power project lawyers Ghana",
  "renewable energy lawyers Ghana",
  "creditor recovery Ghana",
  "debtor restructuring Ghana",
  "trademark registration Ghana",
  "copyright Ghana",
  "patent advisory Ghana",
  "divorce lawyer Ghana",
  "child custody Ghana",
  "adoption law Ghana",
  "maintenance claims Ghana",
  "prosecution defence Ghana",
  "investigation counsel Ghana",
  "enforcement proceedings Ghana",
  "tribunal representation Ghana",
  "ADR Ghana",
  "settlement negotiation lawyers",
  "legal risk assessment",
  "contract review Ghana",
  "regulatory filing Ghana",
  "licensing lawyers Ghana",
  "permit applications legal",
  "public procurement law Ghana",
  "PPP lawyers Ghana",
  "infrastructure projects legal",
  "construction law Ghana",
  "FIDIC contracts Ghana",
  "international commercial contracts",
  "English law contracts Ghana",
  "Ghana companies act advice",
  "directors duties Ghana",
  "minority shareholder protection",
  "corporate secretarial Ghana",
  "annual compliance Ghana",
  "beneficial ownership compliance",
  "sanctions compliance",
  "export control legal",
  "customs and trade compliance",
  "shipping contracts Ghana",
  "agency agreements Ghana",
  "distribution agreements Ghana",
  "franchise law Ghana",
  "technology transactions Ghana",
  "data privacy Ghana",
  "cybersecurity legal Ghana",
  "fintech regulation Ghana",
  "mobile money legal Ghana",
  "payment systems law Ghana",
  "microfinance legal Ghana",
  "savings and loans legal",
  "capital adequacy advisory",
  "prudential regulation Ghana",
  "Bank of Ghana regulation",
  "SEC Ghana compliance",
  "NCA compliance Ghana",
  "GIPC registration lawyers",
  "free zones legal Ghana",
  "special economic zones legal",
  "mining lease lawyers",
  "petroleum agreement Ghana",
  "local content legal Ghana",
  "community engagement legal",
  "CSR legal advisory",
  "whistleblower policy legal",
  "internal investigation lawyers",
  "white collar crime Ghana",
  "asset tracing Ghana",
  "injunction lawyers Ghana",
  "specific performance Ghana",
  "damages claims Ghana",
  "tort lawyers Ghana",
  "negligence claims Ghana",
  "defamation lawyers Ghana",
  "reputation management legal",
  "media law Ghana",
  "entertainment law Ghana",
  "sports law Ghana",
  "education law Ghana",
  "healthcare law Ghana",
  "pharmaceutical regulation Ghana",
  "agriculture law Ghana",
  "agribusiness legal Ghana",
  "insurance law Ghana",
  "reinsurance Ghana",
  "claims dispute insurance",
  "pension regulation Ghana",
  "SSNIT compliance legal",
  "chieftaincy land matters",
  "stool land legal Ghana",
  "leasehold Ghana",
  "freehold title Ghana",
  "land registration Ghana",
  "cadastral issues Ghana",
  "boundary dispute lawyers",
  "easement disputes Ghana",
  "adverse possession Ghana",
  "tenant eviction Ghana",
  "landlord tenant Ghana",
  "commercial tenancy Ghana",
  "rent review Ghana",
  "distress for rent Ghana",
  "specific relief land Ghana",
  "compulsory acquisition Ghana",
  "compensation claims land",
  "environmental permit legal",
  "EPA compliance Ghana",
  "water resources legal Ghana",
  "forestry commission legal",
  "wildlife regulation legal",
  "charity law Ghana",
  "NGO registration Ghana",
  "foundation law Ghana",
  "religious organisation legal",
  "church legal advisory Ghana",
  "mosque trust legal",
  "international NGO Ghana",
  "embassy legal liaison",
  "diplomatic immunity issues",
  "extradition advice Ghana",
  "mutual legal assistance",
  "foreign judgment enforcement Ghana",
  "arbitral award enforcement Ghana",
  "New York Convention Ghana",
  "ICSID arbitration Ghana",
  "LCIA arbitration Ghana",
  "ICC arbitration Ghana",
  "SIAC arbitration Ghana",
  "London arbitration Ghana counsel",
  "international mediation Ghana",
  "dispute board Ghana",
  "expert determination Ghana",
  "early neutral evaluation",
  "litigation funding Ghana",
  "after the event insurance",
  "costs assessment Ghana",
  "security for costs Ghana",
  "interim relief Ghana",
  "Mareva injunction Ghana",
  "Anton Piller Ghana",
  "discovery Ghana",
  "evidence law Ghana",
  "appeal lawyers Ghana",
  "judicial review Ghana",
  "certiorari Ghana",
  "mandamus Ghana",
  "prohibition Ghana",
  "quo warranto Ghana",
  "human rights court Ghana",
  "AU human rights",
  "ECOWAS court representation",
  "OHADA law Africa",
  "OHADA arbitration",
  "SADC legal advisory",
  "COMESA trade law",
  "AfCFTA legal advisory",
  "Pan-African legal services",
  "UK Ghana legal corridor",
  "US Ghana legal corridor",
  "China Ghana investment law",
  "India Ghana business law",
  "Middle East Ghana deals",
  "Europe Ghana transactions",
  "diaspora property Ghana",
  "repatriation legal Ghana",
  "dual citizenship legal Ghana",
  "renunciation advice Ghana",
  "passport legal issues Ghana",
  "immigration appeals Ghana",
  "deportation defence Ghana",
  "asylum advice Ghana",
  "refugee legal Ghana",
  "humanitarian visa Ghana",
  "student visa legal Ghana",
  "dependent visa Ghana",
  "ECOWAS mobility legal",
  "AfCTA mobility legal",
  "remote work legal Ghana",
  "digital nomad tax Ghana",
  "cryptocurrency regulation Ghana",
  "blockchain legal Ghana",
  "NFT legal Ghana",
  "AI regulation legal Ghana",
  "startup legal pack Ghana",
  "term sheet lawyers Ghana",
  "SAFE agreement Ghana",
  "convertible note Ghana",
  "equity crowdfunding legal",
  "venture capital Ghana",
  "private equity Ghana",
  "family office legal Ghana",
  "wealth management legal",
  "trust administration Ghana",
  "executor services legal",
  "power of attorney Ghana",
  "living will Ghana",
  "advance directive Ghana",
  "guardianship Ghana",
  "mental capacity Ghana",
  "elder law Ghana",
  "succession planning Ghana",
  "intestacy Ghana",
  "probate dispute Ghana",
  "will contest Ghana",
  "forced heirship advice",
  "prenuptial agreement Ghana",
  "postnuptial agreement Ghana",
  "cohabitation agreement Ghana",
  "domestic violence protection",
  "restraining order Ghana",
  "marital property Ghana",
  "spousal maintenance Ghana",
  "child support Ghana",
  "parental responsibility Ghana",
  "surrogacy law Ghana",
  "adoption agency legal",
  "foster care legal Ghana",
  "juvenile justice Ghana",
  "youth court Ghana",
  "bail application Ghana",
  "plea negotiation Ghana",
  "sentencing mitigation Ghana",
  "appeal criminal Ghana",
  "habeas corpus Ghana",
  "police complaint legal",
  "EFCC liaison Ghana",
  "economic crimes Ghana",
  "corruption investigation defence",
  "public officer prosecution",
  "parliamentary privilege legal",
  "election petition Ghana",
  "electoral commission legal",
  "political party registration",
  "campaign finance legal",
  "lobbying regulation legal",
  "freedom of information Ghana",
  "RTI request legal Ghana",
  "transparency legal Ghana",
  "procurement challenge Ghana",
  "bid protest Ghana",
  "state contract dispute",
  "sovereign immunity Ghana",
  "state liability Ghana",
  "municipal law Ghana",
  "local government legal",
  "by-law drafting Ghana",
  "statutory interpretation Ghana",
  "legislative drafting support",
  "law reform submissions",
  "legal policy advisory",
  "law reform Ghana",
  "access to justice Ghana",
  "pro bono Ghana",
  "legal aid referral Ghana",
  "community legal education",
  "law clinic partnership",
  "university law lecturers",
  "commercial law lecturer",
  "continuing legal education",
  "law firm training Ghana",
  "banking executive training legal",
  "compliance officer training",
  "board training governance",
  "director induction legal",
  "whistleblower training legal",
  "AML training Ghana",
  "KYC legal standards Ghana",
  "CDD enhanced due diligence",
  "PEP screening legal",
  "sanctions screening legal",
  "transaction monitoring legal",
  "SAR filing legal Ghana",
  "regulatory examination prep",
  "consent order negotiation",
  "regulatory settlement Ghana",
  "licence revocation defence",
  "fit and proper person Ghana",
  "director disqualification",
  "insider dealing Ghana",
  "market abuse Ghana",
  "takeover code Ghana",
  "mandatory offer Ghana",
  "squeeze out Ghana",
  "scheme of arrangement Ghana",
  "creditors scheme Ghana",
  "company voluntary arrangement",
  "administration Ghana",
  "liquidation Ghana",
  "receiver appointment Ghana",
  "fixed charge enforcement",
  "floating charge Ghana",
  "debenture enforcement",
  "guarantee enforcement Ghana",
  "surety defence Ghana",
  "indemnity claims Ghana",
  "contribution proceedings",
  "subrogation claims Ghana",
  "insurance subrogation",
  "contribution insurance",
  "policy wording review",
  "coverage dispute Ghana",
  "bad faith insurance",
  "professional indemnity Ghana",
  "D&O liability Ghana",
  "E&O insurance legal",
  "medical malpractice Ghana",
  "legal malpractice defence",
  "chambers negligence",
  "costs dispute lawyers",
  "fee arbitration Ghana",
  "retainer agreement Ghana",
  "conditional fee Ghana",
  "damages based agreement",
  "legal expenses insurance",
  "third party funding rules",
];

function combineKeywords() {
  const set = new Set();

  for (const phrase of [
    ...FIRM_NAMES,
    ...PRACTICE_AREAS,
    ...CLIENT_TYPES,
    ...INTENT,
    ...GOVERNANCE,
    ...EXTRA,
  ]) {
    set.add(phrase);
  }

  for (const firm of FIRM_NAMES.slice(0, 3)) {
    for (const loc of LOCATIONS) {
      set.add(`${firm} ${loc}`);
    }
  }

  for (const area of PRACTICE_AREAS) {
    for (const loc of ["Ghana", "Accra", "West Africa"]) {
      set.add(`${area} ${loc}`);
      set.add(`${area} lawyer ${loc}`);
      set.add(`${area} attorneys ${loc}`);
    }
  }

  for (const type of FIRM_TYPES) {
    for (const loc of LOCATIONS) {
      set.add(`${type} ${loc}`);
      set.add(`${loc} ${type}`);
    }
  }

  for (const client of CLIENT_TYPES) {
    set.add(`legal services for ${client}`);
    set.add(`lawyers for ${client} Ghana`);
  }

  return [...set];
}

/** @type {string[]} */
export const SEO_KEYWORDS = combineKeywords();

export const SEO_KEYWORDS_STRING = SEO_KEYWORDS.join(", ");
